### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by ankane** [ankane/rover#1]
Please create a new issue to discuss any ideas or share your own.

0.3.0

- [x] Use `KeyError` instead of `ArgumentError` for missing columns for did_you_mean suggestions
- [x] Drop support for Ruby < 2.7
- [x] Expand types for consistency - `int` -> `int64`, `uint` -> `uint64`, `float` -> `float64`
- [x] Raise `ArgumentError` when no columns passed to `group`

Ideas

- [x] Dummy variables
- [x] Group calculations (group count/sum/mean/median/min/max)
- [x] Better support for types
- [ ] Method to convert two column data frame to hash (1st column keys, 2nd column values)
- [ ] Support creating data frame from Numo array
- [ ] Summary
- [ ] More array-like methods - https://ruby-doc.org/core-2.7.1/Array.html
- [ ] Move CSV parsing to C/C++ for performance

Visualization

- [x] Add support for multiple series - [group](https://github.com/ankane/rover/issues/20#issuecomment-1019389504) option
- [ ] Add `plot` method for vectors

Maybe

- [x] Return data frame instead of hash from group calculations - `group_df` branch
- [ ] Sort values after grouping (either by keys or calculation value)
- [ ] More types - `string`, `datetime`, etc
- [ ] Treat string and symbols the same for keys (indifferent access)
- [ ] `in_time_zone` method on vector (requires Active Support)

Long-term

- [ ] Test out performance of DuckDB (possible engine)

**Comment by dansbits** [comment]
Yes! I've been considering the idea of building a dataframe on Numo myself - I think it would be a big step forward for Ruby. Thank you for getting the ball rolling - I hope I can contribute.

For group calculations, are you thinking something similar to the pandas `.groupby(...).sum` style?

**Comment by ankane** [comment]
Yeah, I'm currently thinking `df.group(col).sum`, which should be familiar to Rails users.

**Comment by ankane** [comment]
Just added grouping on master. Let me know what you think:

```ruby
df.group("category").max("price")
```

**Comment by dansbits** [comment]
Yeah. I get the draw of simplicity in returning a hash. I admit my personal bias is toward optimizing for notebook output, but recognize this could be useful in other contexts. I think the current output format would make it difficult to join the aggregations back to another dataframe, or feed it to a plotting library. Is there maybe a middle ground where the hash can easily be used to create a new data frame?

Something like:
```ruby
df.group([:x, :y]).count
# => [{ x: "foo", y: "bar", count: 12}, {x: "baz", y: "bar", count: 31 }, ...]
```

**Comment by ankane** [comment]
Agree it's much better for joining with other data frames. I've changed it to return a data frame on master.

**Comment by HansHauge** [comment]
Hey @ankane is it currently possible to set an entire column to the sum of two other columns?

Like `df[:a] = df[:b] + df[:c]` for example?

**Comment by ankane** [comment]
@HansHauge that should work. Are you running into an error?

**Comment by HansHauge** [comment]
No, I was just wondering if it was implemented. Just started messing around with Rover. So far it's very cool. Thank you for all the cool stuff you build ❤️

**Comment by y8** [comment]
Hi! Thanks for awesome library! 

It would be very helpful to be able to define index column for DataFrames. Like:

```ruby

df = Rover::DataFrame.new([
   {price: 1, freq: 0.66, uuid: "adec42wee", }, 
   {price: 420, freq: 5.5, uuid: "raeEr34"}
 ])
 
df.index_by :uuid

df.at "raeEr34"
# => {price: 420, freq: 5.5, uuid: "raeEr34"}
```

**Comment by baarkerlounger** [comment]
@ankane do you have any thoughts on Parquet support?

**Comment by ankane** [comment]
Thanks for the suggestions.

@y8 I'd like to keep things simple for now, but will consider this for the future.

@baarkerlounger I'm not exactly sure what that'll involve, but happy to discuss more if someone wants to prototype it.

**Comment by Ashvith** [comment]
@ankane I would like to contribute to this project. Any easy ideas that I should look into?
