### ISSUE TITLE
Joining DataFrame when a column has only nil values changes the column type

### ISSUE THREAD

**Issue by DaddyWozBucks** [ankane/rover#10]
Firstly good job - using the gem for wrangling large data sheets. 

Having a bit of an issue when joining to DataFrames together. The values in the column are nil (column type :object) until I join them with another Frame and the column type changes to :float, rendering NaN instead of nil.

Here is an example to reproduce

`
base_rover = Rover::DataFrame.new(
            {
              test: [nil, nil, nil],
              code: %[ a b c]
            },
            types: { test: :object, code: :object}
          )`

`
 join_rover = Rover::DataFrame.new(
            {
              name: %w[A B C],
              code: %[ a b c]
            },
            types: { name: :object, code: :object}
          )
`
 `result = base_rover.inner_join(join_rover, on: :code)`
 ` result[:test].type`

**Comment by DaddyWozBucks** [comment]
Digging in a bit I solved it by changing line 501 of `data_frame.rb` to `DataFrame.new(vectors, types: types.merge(other.types))`. I have a pr ready to open if you want?

**Comment by ankane** [comment]
Hey @DaddyWozBucks, thanks for reporting! Happy to have a PR (a test case would be good, too).

**Comment by ankane** [comment]
Should be fix in the commit above. Thanks again for reporting.
