### ISSUE TITLE
is there a way to create a rover DF from an ActiveRecord::Result ?

### ISSUE THREAD

**Issue by jcquarto** [ankane/rover#15]
I have some data I pull from AR via a raw SQL statement (it's too complex to use AREL. 

`data = ActiveRecord::Base.connection.exec_query( ...very complex SQL here ...)`

when I try to dataframe it
`df = Rover::DataFrame.new(data)`

I get the error
`Cannot cast to data frame: ActiveRecord::Result`

which was a bit surprising. But, the following works:
`df = Rover::DataFrame.new(data.to_json)`

(having, of course, nothing to do with json, haha)

question: is that as expected?   Could Rover possibly detect it's an AR Result and automatically convert it to an array of hashes?

**Comment by ankane** [comment]
Good idea, just added.
