### ISSUE TITLE
Failure when Parquet file contains rows with `nil` values.

### ISSUE THREAD

**Issue by rngtng** [ankane/rover#17]
First, thanks a lot for this great gem. I made my life already a lot easier dealing with Parquet file!

I only now ran into an issue we a column of type Int32 could contain `(null)` / `nil` values too. In that case it blows up with:

```
/usr/local/bundle/gems/rover-df-0.2.6/lib/rover.rb:88:in `cast': no implicit conversion from nil to integer (TypeError)
	from /usr/local/bundle/gems/rover-df-0.2.6/lib/rover.rb:88:in `block in parquet_to_df'
	from /usr/local/bundle/gems/red-arrow-6.0.1/lib/arrow/column-containable.rb:27:in `each'
	from /usr/local/bundle/gems/red-arrow-6.0.1/lib/arrow/column-containable.rb:27:in `each_column'
	from /usr/local/bundle/gems/rover-df-0.2.6/lib/rover.rb:82:in `parquet_to_df'
	from /usr/local/bundle/gems/rover-df-0.2.6/lib/rover.rb:24:in `read_parquet'
	from /app/lib/reader/parquet.rb:20:in `read'
	from /app/lib/migrator.rb:20:in `call'
	from ./src/migrate.rb:33:in `<main>'
```

Debugging shows that that's the reason:
```
Numo::Int32.cast([0, 0, nil, nil])
```

Is there any smart way to allow `nil` values?

**Comment by ankane** [comment]
Hey @rngtng, integer columns don't currently have a way to represent `nil` values, but I've added a `types` option you can use to read the column as a float type (which converts them to NaN) or an object type (which leaves them as `nil`).

```ruby
df = Rover.read_parquet("data.parquet", types: {"a" => :object}) # :float, or :float32
```

**Comment by ankane** [comment]
Another idea is automatic conversion of integer columns to `:float` and boolean columns to `:object`, similar to how the following are handled.

```ruby
p Rover::DataFrame.new({"a" => [1, nil, 2]}).types
p Rover::DataFrame.new({"a" => [true, nil, false]}).types
```

**Comment by rngtng** [comment]
cool thanks a lot, that worked!
