### ISSUE TITLE
Filtering on column value

### ISSUE THREAD

**Issue by hi-tech-jazz** [ankane/rover#18]
If I create a dataframe like this: 

`df = Rover::DataFrame.new([{x: true}])`

I get the expected behavior by filtering in the following ways:
```
df[df[:x] == 1]      # => dataframe of size 1
df[df[:x] == 0]      # => empty dataframe
```
However I cant use `!=` without raising an error:

```
irb(main):139:0> df[df[:x] != 0]
/Users/hi-tech-jazz/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rover-df-0.2.6/lib/rover/vector.rb:120:in `block (2 levels) in <class:Vector>': undefined method `ne' for Numo::Bit#shape=[1] (NoMethodError)
[1]:Numo::Bit
```
Am I missing something? Thanks in advance.

**Comment by ankane** [comment]
Hey @hi-tech-jazz, thanks for reporting! You should be able to use `df[!df[:x]]` for now, but would be good to make `df[df[:x] != false]` work in the future. Also, `df[:x] == number` should probably return false for all rows since booleans and numbers aren't equal in Ruby.

**Comment by hi-tech-jazz** [comment]
Thanks for the swift reply @ankane! Of course, that makes sense.
