### ISSUE TITLE
Any plan for DateTime support? 

### ISSUE THREAD

**Issue by weqopy** [ankane/rover#19]
Is there a plan for DateTime support for rover? Like Daru::DateTimeIndex in [Daru](https://github.com/SciRuby/daru) 
![image](https://user-images.githubusercontent.com/10494196/148628318-e0753964-944e-4e02-90a9-7f62395da435.png)

**Comment by ankane** [comment]
Hey @weqopy, what datetime features are you interested in? You can currently do:

```ruby
ds = ["2022-01-01", "2022-01-02", "2022-01-04"]
df = Rover::DataFrame.new(ds: ds.map { |v| DateTime.parse(v) }) # or Date.parse, Time.parse, etc
```

**Comment by weqopy** [comment]
@ankane Thanks, `df = Rover::DataFrame.new(ds: ds.map { |v| DateTime.parse(v) })` is useful.
But yes, there are more features I'm interested in:

1. `df['2022']` to get whole year's data
2. `df['2022-01']` to get whole month's data

And my real demand is use `df` for data like:
```
=> #<Daru::DataFrame(4x3)>
                   val  total_val     net_at
 2022-01-07     1.0000     1.0000 2022-01-07
 2022-01-09     1.0000     1.0000 2022-01-09
 2022-01-08     1.0000     1.0000 2022-01-08
 2022-01-10     1.0001     1.0001 2022-01-10
```

So Daru is not totally support this situation actually. https://github.com/SciRuby/daru/pull/544

**Comment by ankane** [comment]
There aren't currently plans to add indexes, but you can do:

```ruby
df[df[:ds].map { |v| v.month == 1 && v.year == 2022 }]
```

**Comment by weqopy** [comment]
I'll try it. Thanks!

> There aren't currently plans to add indexes, but you can do:
> 
> ```ruby
> df[df[:ds].map { |v| v.month == 1 && v.year == 2022 }]
> ```
