### ISSUE TITLE
Dataframe plot generated won't display in iPython Notebook on next session.

### ISSUE THREAD

**Issue by Ashvith** [ankane/rover#24]
Executing the notebook in the initial session, and saving in Jupyter (and VSCode as well) looks fine:
![merge_from_ofoct](https://user-images.githubusercontent.com/9512421/151666305-19d44a60-1a3b-40e0-82bd-434df68254b9.jpg)

But when the same notebook is opened again, it only shows the first most data frame log (That is, only the `df = Rover.read_csv("stocks.csv")` cell).
![merge_from_ofoct(1)](https://user-images.githubusercontent.com/9512421/151666335-641a68c7-f5f9-4a0d-8adc-dfc42e1d1739.jpg)

**Comment by ankane** [comment]
Hey @Ashvith, unfortunately, I'm not able to reproduce. Are there any errors in the JavaScript console?

**Comment by Ashvith** [comment]
Tried the following activities after executing the notebook once:
1) Quit Jupyter notebook safely, Hit `Ctrl + S`, and reopened the .ipynb file.
2) Killed Jupyter notebook forcibly, by closing the terminal halfway, and reopened the .ipynb file.

The charts were preserved in both instances. However, when I used VSCode, that's where things started to get messed up. It looks like when I open (running not necessary, just saving is enough to trigger), and try opening it again on either of the notebook IDEs, it stays blank. In rare cases, some of the charts are preserved randomly, while some are missing.

VSCode is probably causing this issue to show up in itself, as well as Jupyter.

> Hey @Ashvith, unfortunately, I'm not able to reproduce. Are there any errors in the JavaScript console?

Yes, there are some errors as well as warnings in the browser.
![Screenshot from 2022-01-31 09-25-30](https://user-images.githubusercontent.com/9512421/151736832-ebc194a3-4bcd-476d-b44e-5251c5412541.png)

**Comment by ankane** [comment]
I haven't tried running notebooks in VSCode, but it sounds like saving may be removing output from the `ipynb` file. I'd try comparing the file before and after to see if that's the case.

Also, from what I can tell, the errors/warnings don't seem related to Vega.

**Comment by Ashvith** [comment]
Closing this issue, I think the VSCode Jupyter extension is messing up something on the inside. When I open the Developer Tool for VSCode, I get this:

![Screenshot from 2022-02-02 21-14-50](https://user-images.githubusercontent.com/9512421/152187398-ccc18833-7ce8-4334-b494-580371c33f2f.png)

**Comment by ankane** [comment]
From that log, my guess is Vega is being loaded before `require.js`, causing it to error on [this line](https://github.com/ankane/vega-ruby/blob/985b7e02369476de3e7e880365ba7c6cd03def89/lib/vega/spec.rb#L33). I'm not sure if there's another pattern Vega Ruby could use to avoid that, but it seems like different behavior than running it directly in Jupyter.

**Comment by ankane** [comment]
Cleaning up issues
