### ISSUE TITLE
No means to "describe" DataFrames

### ISSUE THREAD

**Issue by ghost** [ankane/rover#25]
There is a need to implement the `describe` function for data frame, similar to the one in pandas. The attributes available in pandas are:
- [x] **count**
- [ ] **unique**
- [ ] **top**
- [ ] **frequency**
- [ ] **mean**
- [ ] **std**
- [ ] **min**
- [ ] **25**%
- [ ] **50**%
- [ ] **75**%
- [ ] **max**

**Comment by Ashvith** [comment]
@ankane in this case, if the cell is a `String` type, the execution stops in between for all the given functions (including `percentile`), except `count`. I was thinking that if the type does not match, we could simply return "N/A".

**Comment by ankane** [comment]
Cleaning up issues
