### ISSUE TITLE
Add bin/console for interacting with the pre-build library

### ISSUE THREAD

**Issue by Ashvith** [ankane/rover#27]
Currently, it is very difficult to work on this gem, as we have to rebuild, and reinstall it every time we work on a patch. Addition of console will improve this process.

**Comment by ankane** [comment]
Hey @Ashvith, thanks for the suggestion and PR.

For testing outside of `rake test`, you can create a Gemfile that includes:

```ruby
gem "rover-df", path: "path/to/rover"
```

And at the top of your Ruby script, include:

```ruby
require "bundler/setup"
Bundler.require(:default)
```

To avoid reinstalling on changes, so I don't think binstubs are needed (in iRuby, you'll need to select one of the Restart options in the Kernel menu).
