### ISSUE TITLE
Methods for casting vectors to different types

### ISSUE THREAD

**Issue by dansbits** [ankane/rover#3]
It could be useful to have some methods to cast vectors to different data types. I often run into cases where data might be stored as a Float in a CSV but what I actually want is an integer or string. Would be curious on the right interface for this. My initial thought was to mimic Numo's API. Something like:

```ruby
float_vector = Rover::Vector.new([1.0,2.0,3.0])
float_vector.cast_to(:int64)
float_vector.cast_to(:string) # I know this is an RObject in Numo
```
Could also try to be consistent with Ruby conventions, but would need to give the user the option to specify data types.
```ruby
class Rover::Vector
  ...
  def to_i(type: :int64)
  end
  ...
end
```

I think this is a separate feature but it would be nice to be able to specify this at the time a CSV is read as well.

**Comment by ankane** [comment]
Just pushed out a new release with the `to` method and a few types options, including one for `read_csv`: https://github.com/ankane/rover#types

**Comment by dansbits** [comment]
Thanks! Closing this issue.
