### ISSUE TITLE
Possible DuckDB implementation?

### ISSUE THREAD

**Issue by Ashvith** [ankane/rover#30]
I would like to try out Rover with DuckDB. Any starters that I should keep in mind?

**Comment by ankane** [comment]
Hey @Ashvith, I've done a little prototyping with this and think it's probably easiest to start a new gem for it since most of the internals will change.

**Comment by Ashvith** [comment]
@ankane someone is already working on a Ruby implementation (using the C++ library) - [ruby-duckdb](https://github.com/suketa/ruby-duckdb). What do you think?

**Comment by ankane** [comment]
That's what I used for my prototype (you'll likely want to build on top of it).
