### ISSUE TITLE
Move CSV parsing to C/C++ for performance

### ISSUE THREAD

**Issue by ghost** [ankane/rover#31]
So, I did a little bit of research to find out if C/C++ based libraries exists for Ruby, and came across a few of them:
- [fastcsv](https://github.com/jpmckinney/fastcsv)
- [fastest-csv](https://github.com/brightcode/fastest-csv)
- [ccsv](https://github.com/evan/ccsv)
- [rscsv](https://github.com/lautis/rscsv)

Is it possible that we can reuse them? Or do we have to start with binding our own implementation or maybe the `libcsv` library available on *nix systems through their respective package managers?

**Comment by heronshoes** [comment]
How about to use Red Arrow to parse csv?

This is an article by the maintainer of standard CSV lib.
https://www-clear--code-com.translate.goog/blog/2018/12/25.html?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=ja&_x_tr_pto=wapp
(sorry it is originally in japanese => https://www.clear-code.com/blog/2018/12/25.html)

It was written when Ruby 2.6.0 has released. He wrote;

- CSV is fastest Ruby level parser (16 iterating per 100ms).
- fastest-csv gem is written in C, ~5 times faster (76 iter. per 100ms).
- Apache Arrow is 14 times faster than pure Ruby CSV (223 iter. per 100ms).

We are already using Arrow for parquet parser in this gem.
Arrow accepts csv, json, arrow and orc format.
Congratulations! They are in **SAME STYLE** !!

```
require "arrow"
table = Arrow::Table.load("data.csv")
table = Arrow::Table.load("data.json")
table = Arrow::Table.load("data.arrow")
table = Arrow::Table.load("data.orc")

require "parquet"
table = Arrow::Table.load("data.parquet")
```

So **simply calling `Rover.read_parquet("data.csv")` will parse
csv by Arrow with current Rover code**.

Some csv failed to parse at my test, but the goal will be close.

**Comment by Ashvith** [comment]
@heronshoes What do you think about using DuckDB's CSV loading? [DuckDB - CSV Loading](https://duckdb.org/docs/data/csv). If you check the Idea List issues, there is also a plan for experimental DuckDB integration. By the way, I have tried to recreate an old gem (rcsv), but the performance isn't great. There is also this [interesting read](https://duckdb.org/2021/12/03/duck-arrow.html).

**Comment by ankane** [comment]
Hey @Ashvith and @heronshoes, thanks for sharing some ideas. Ideally, CSV parsing doesn't require any additional system libraries to be installed by the user while still supporting most/all of Ruby's CSV options. To achieve best performance, it'd ideally write to Numo directly instead of converting all values to Ruby first. I think the most straightforward way to do this would be to embed an existing C/C++ CSV library and write code to have it handle Ruby's CSV options.

**Comment by ankane** [comment]
Cleaning up issues
