### ISSUE TITLE
DataFrame#dup does not copy Vectors in it

### ISSUE THREAD

**Issue by heronshoes** [ankane/rover#33]
Hi, I love this cute and nice gem 👍.

DataFrame#dup does not duplicate Vectors in it,
I think it is better to copy deeply.

```
df = Rover::DataFrame.new({x: [1, 2, 3] })
df2 = df.dup
df2[:x][1] = 0
df  # => DataFrame{x: [1, 0, 3]}

df.eql? df2   #=> false (dataframe is duplicated)

df[:x].eql? df2[:x]  #=> true (vector is same)
```

To fix this, both DataFrame#dup and Vector#dup should be modified.

**Comment by ankane** [comment]
Hey @heronshoes, `dup` performs a shallow copy, following the [Ruby convention](https://ruby-doc.org/core-3.1.1/Object.html#method-i-dup) (similar to classes like `Hash`).

```ruby
h = {x: [1, 2, 3]}
h2 = h.dup
h[:x][1] = 0
p h2
```

**Comment by heronshoes** [comment]
Hi @ankane, thank you for your comment. I understood that `dup` follows `Hash` like behavior.

Simply I made mistake to use `dup` for copying a DataFrame to keep original one.

**Comment by ankane** [comment]
Hey @heronshoes, looked into this more and the `clone` and `dup` methods for vectors weren't copying properly. Fixed in the commit above. Thanks for reporting!

Also, added a `deep_dup` method to data frames for deep copies.

**Comment by heronshoes** [comment]
Thank you @ankane, I'm happy to contribute.

Also, I will use `deep_dup` for my incoming proposal.
