### ISSUE TITLE
QuestDB integration

### ISSUE THREAD

**Issue by scart88** [ankane/rover#44]
I'm trying to integrate [QuestDB](https://questdb.io/) with Rails and there is no official client for Ruby.

They are recommending the InfluxDB Line Protocol as it has the best performance with the following example for Ruby.

```ruby
require 'socket'
HOST = 'localhost'
PORT = 9009
# Returns the current time in nanoseconds
def time_in_nsec
    now = Time.now
    return now.to_i * (10 ** 9) + now.nsec
end
begin
    s = TCPSocket.new HOST, PORT
    # Single record insert
    s.puts "trades,name=client_timestamp value=12.4 #{time_in_nsec}\n"
    # Omitting the timestamp allows the server to assign one
    s.puts "trades,name=client_timestamp value=12.4\n"
    # Streams of readings must be newline-delimited
    s.puts "trades,name=client_timestamp value=12.4\n" +
            "trades,name=client_timestamp value=11.4\n"
rescue SocketError => ex
    puts ex.inspect
ensure
    s.close() if s
end
```

I notice their [Python client](https://github.com/questdb/py-questdb-client) is using data frames to ingest data and I found the Rover gem.

Do you have any advice on how can I move forward in integrating the Data Frames created by Rover with QuestDB?

Thank you very much!

**Comment by ankane** [comment]
Hi @scart88, you should be able to use `each_row` iterate over the rows of the data frame (or select rows by index in batches). However, if you're not using Rover already, there's no reason to introduce it for this (you can use an array to collect data points and iterate over that instead).
