### ISSUE TITLE
Column accessor methods

### ISSUE THREAD

**Issue by MadBomber** [ankane/rover#46]
I looking at converting a large application over from Daru::DataFrame to Rover::DataFrame.   One of the things that I am missing is simple vector accessor methods.  For example:

```ruby
df[:a] #=> the "a" column vector ...
df.a  #=> that same 'a' column vector ...

df[:a].any_method
df.a.any_method #=> same result
```

**Comment by ankane** [comment]
Check out https://github.com/ankane/rover#selecting-data

**Comment by MadBomber** [comment]
@ankane  I did.  I saw nothing there that precludes using an accessor method in addition to the [] method.

Check out this test code I put together to verify duel access ... https://raw.githubusercontent.com/MadBomber/experiments/master/stocks/rover_test.rb

Here is the result I get on STDOUT 

```text
12:59:45 3.2.2 master elk:stocks $ ./rover_test.rb
2023-10-03 12:59:54.082073 DEBUG Source:  ./rover_test.rb:70:in `<main>'
2023-10-03 12:59:54.082073 DEBUG aapl_df.keys -=> [:date, :open, :high, :low, :close, :adj_close, :volume]
2023-10-03 12:59:54.082073 DEBUG aapl_df[:adj_close] -=> #<Rover::Vector [37.994484, 34.209953, 35.670361, 35.590965, 36.269436, ...]>
2023-10-03 12:59:54.083025 DEBUG Source:  ./rover_test.rb:77:in `<main>'
2023-10-03 12:59:54.083025 DEBUG aapl_df.adj_close -=> #<Rover::Vector [37.994484, 34.209953, 35.670361, 35.590965, 36.269436, ...]>
12:59:54 3.2.2 master elk:stocks $ # you wish you had bought aapl 5 years ago!
13:00:51 3.2.2 master elk:stocks $
```

**Comment by ankane** [comment]
Thanks for the additional context. I'm not a fan of adding separate methods for each column since it could collide with existing methods.

**Comment by MadBomber** [comment]
You are welcome @ankane .  I am a fan of your work.  I agree that method collision is a possibility; however, if this feature were optional the responsibility for avoiding or dealing with conflicts is that of the application and not the library - much like cleaning your data before using it.

My research into the various data frame libraries available has finally opened my eyes to the fact that my application's needs are simplistic.  I can do what I what to do with a wrapper around a Hashie::Mash object.  When I need to apply some of the more complex calculations outside of simple statistics I can easily convert my simplistic in memory data store to a Rover::DataFrame, do my business, take the answers and run back to the mundane.
