### ISSUE TITLE
Comparing one DataFrame to another breaks when values are big decimals

### ISSUE THREAD

**Issue by DaddyWozBucks** [ankane/rover#5]
In my spec I have a DataFrame with my expected values and one generated by my code. When checking to see if the values are the same I noticed two things.
1) It is sensitive to the order of the keys
2) It breaks with BigDecimals

`NoMethodError: undefined method `eq' for 0.1e3:BigDecimal
from /.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rover-df-0.2.0/lib/rover/vector.rb:120:in `eq'`

**Comment by ankane** [comment]
Hey @DaddyWozBucks, can you share a minimal example to reproduce?

**Comment by ankane** [comment]
Closing due to no response
