### ISSUE TITLE
Lambda?

### ISSUE THREAD

**Issue by willhaslett** [ankane/rover#7]
Hi. I'm exploring this gem. I don't see any references to having a lambda operate on a column. Is that possible?

**Comment by willhaslett** [comment]
Or really, any way to iterate over or a row and apply a function, whether it's a vector operation or just a loop?

**Comment by epugh** [comment]
Here is how I've used this gem, and I'm sure there are MUCH better ways of using it..  https://github.com/o19s/quepid/blob/spike_adding_multiple_raters/app/controllers/analytics/ratings_controller.rb#L26

**Comment by ankane** [comment]
Hey @willhaslett, you can use `map`, `map!`, `each`, and `each_with_index` to iterate over values in a column (tries to follow the same API as Ruby arrays).

**Comment by ankane** [comment]
Added those methods to the docs.

@epugh Thanks for sharing. For the end of `create_df_for_user`, you should be able to do: (no loop required 🎉 )

```ruby
df[:querydoc_id] = df['query_id'] + "!" + df['doc_id']
```

Saw you're interested in more examples in https://github.com/ankane/rover/issues/8#issuecomment-853018374, so feel free to create a new issue if you want to chat more.
