### ISSUE TITLE
Support creating data frame from Numo array

### ISSUE THREAD

**Issue by kdiogenes** [ankane/rover#8]
Hey, @ankane,

I was trying to create a DataFrame from a numo array and found that this is an idea: https://github.com/ankane/rover/issues/1

Something like this is OK or you see any performance issue:

```ruby
columns = %w(a b c)
matrix = [[0.0, 1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0, 9.0], [10.0, 11.0, 12.0, 13.0, 14.0]]
matrix.to_h { |row| [columns.shift, row] }
```
Do you think it's ok to pass the columns in the DataFrame initializer?

**Comment by ankane** [comment]
Hey @kdiogenes, passing a hash of columns should be the most efficient way to create a data frame from a Numo array.

```ruby
matrix = Numo::DFloat.new(4, 2).seq
Rover::DataFrame.new({
  a: matrix[true, 0],
  b: matrix[true, 1]
})
```

**Comment by epugh** [comment]
I appreciate seeing these conversations, I would love to see more examples to help me learn how to use Rover ;-)
