### ISSUE TITLE
Sort By multiple rows?

### ISSUE THREAD

**Issue by epugh** [ankane/rover#9]
I have a table where I want to sort by first `query_text`, and then within each of those, by `doc_id`.   

I tried, though without expecting success, to do `@df.sort_by! { |r| r['query_text', 'doc_id'] }`

Any suggestions?

https://github.com/o19s/quepid/pull/263/commits/c943d9baab2217be7cdf70877594509d13569fdc

**Comment by ankane** [comment]
Hey @epugh, `sort_by!` yields a hash (you can print `r` to confirm), so it'll be:

```ruby
@df.sort_by! { |r| [r['query_text'], r['doc_id']] }
```

**Comment by epugh** [comment]
This worked great!
